newspapers:
  cronSchedule: "0 0 * * * *"
  syncs:
    - name: "VG"
      url: "https://www.vg.no/"
      plusSelector: "type-icon pluss-icon"
      articleSelector: "<article"
    - name: "Avisa Oslo"
      url: "https://www.ao.no/"
      plusSelector: data-adppaywall="true"
      articleSelector: "<article"
    - name: "Amta"
      url: "https://www.amta.no/"
      plusSelector: data-adppaywall="true"
      articleSelector: "<article"