spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.hibernate.ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-ui

newspaper:
  schedule: 15
  vg:
    url: https://www.vg.no/
    pluss-selector: type-icon pluss-icon
    article-selector: <article
  ao:
    url: https://www.ao.no/
    pluss-selector: data-adppaywall="true"
    article-selector: <article
  amta:
    url: https://www.amta.no/
    pluss-selector: data-adppaywall="true"
    article-selector: <article

